### ISSUE TITLE
Adding Chrome Support

### ISSUE THREAD

**Issue by adnanrahic** [TheAdnan/focustube#1]
Hey,
Would it be possible to add this extension to the Chrome store? If you would be interested in creating support for this, I'd be glad to give a helping hand.
Cheers!

**Comment by TheAdnan** [comment]
Sure! Thanks!

**Comment by TheAdnan** [comment]
Create pull request to the `chrome` branch

**Comment by adnanrahic** [comment]
Awesome. Will jump on this ASAP.
