### ISSUE TITLE
Update the readme with screenshots

### ISSUE THREAD

**Issue by TheAdnan** [TheAdnan/focustube#3]
Update the README with screenshots of usage of the extension.

**Comment by Skuhoo** [comment]
Sure, I can do this

**Comment by Ipaye** [comment]
do you still need help with this?

**Comment by TheAdnan** [comment]
@Ipaye no, but you can make a PR, for the sake of the Hacktoberfest 😃

**Comment by Ipaye** [comment]
Lol. Okay. Would do that
